services:
  - type: web
    name: news-scraper
    env: python
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y wget unzip
      sudo apt-get install -y google-chrome-stable
      wget https://chromedriver.storage.googleapis.com/$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
      unzip chromedriver_linux64.zip
      chmod +x chromedriver
      sudo mv chromedriver /usr/local/bin/
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn news_scraper.wsgi:application
    envVars:
      - key: DEBUG
        value: False
